namespaces:
  - name: site-a-monitoring
  - name: site-a-ingress

machineConfigPools:
  - name: infra
    role: infra
    ignitionConfig: |
      {
        "ignition": {
          "version": "3.2.0"
        }
      }
