apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hub-infrastructure
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
        - name: site-a-hub-cluster
          path: sites/site-a/hub-clusters/hub-a-values.yaml
        - name: site-b-hub-cluster
          path: sites/site-b/hub-clusters/hub-b-values.yaml
  template:
    metadata:
      name: '{{.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/IdanHenik/hcp-gitops-demo.git
        path: hub-infrastructure-chart
        targetRevision: main
        helm:
          valueFiles:
            - global-values/values.yaml
            - '{{path.dirname}}/site-hub.yaml'
            - "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  #sites/{{path.dirname | split "/" | nth 1}}/site-hub.yaml