apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-clusters
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/IdanHenik/hcp-gitops-demo.git
        revision: main
        directories:
          - path: ../sites/*/clusters/*.yaml
  template:
    metadata:
      name: '{{path.basename}}-tenant-cluster'
    spec:
      project: default
      source:
        repoURL: https://github.com/IdanHenik/hcp-gitops-demo.git
        path: tenant-chart
        targetRevision: main
        helm:
          valueFiles:
            - ../global-values/values.yaml
            - ../sites/{{path.dirname | split "/" | nth 1}}/site.yaml
            - ../"{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
