apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.etcdEncryptionKey.name }}
  namespace: {{ .Values.namespace }}
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
data:
  key: TMHG6olDllzLQHWnNHByrxJ9Yg1rCAcHpgzRd4GK0cs=
type: Opaque
