apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
data:
  .dockerconfigjson: {{ .Values.pullSecret.data }}
type: kubernetes.io/dockerconfigjson
