namespaces:
  - name: openshift-monitoring
  - name: openshift-ingress
  - name: clusters

operators:
  - name: cluster-monitoring-operator
    namespace: openshift-monitoring
    source: redhat-operators
    channel: stable
  - name: cluster-ingress-operator
    namespace: openshift-ingress
    source: redhat-operators
    channel: stable

imageContentSources:
  - source: quay.io/openshift-release-dev/ocp-release
    mirrors:
      - global.registry.local/ocp-release
